version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: selfservice-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - selfservice-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: selfservice-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - selfservice-network

volumes:
  postgres_data:
    name: selfservice-postgres-data

networks:
  selfservice-network:
    name: selfservice-network
    driver: bridge 